// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsim.h for the primary calling header

#ifndef _VSIM_SIM_H_
#define _VSIM_SIM_H_  // guard

#include "verilated_heavy.h"
#include "Vsim__Dpi.h"

//==========

class Vsim__Syms;
class Vsim_VerilatedVcd;
class Vsim_VexRiscv;


//----------

VL_MODULE(Vsim_sim) {
  public:
    // CELLS
    Vsim_VexRiscv* VexRiscv;
    
    // PORTS
    VL_OUT8(sim_trace,0,0);
    VL_IN8(sys_clk,0,0);
    VL_OUT8(serial_source_valid,0,0);
    VL_IN8(serial_source_ready,0,0);
    VL_OUT8(serial_source_data,7,0);
    VL_IN8(serial_sink_valid,0,0);
    VL_OUT8(serial_sink_ready,0,0);
    VL_IN8(serial_sink_data,7,0);
    VL_OUT(gpio_oe,31,0);
    VL_OUT(gpio_o,31,0);
    VL_IN(gpio_i,31,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__int_rst;
        CData/*0:0*/ __PVT__soc_rst;
        CData/*1:0*/ __PVT__reset_storage;
        CData/*0:0*/ __PVT__reset_re;
        CData/*0:0*/ __PVT__scratch_re;
        CData/*0:0*/ __PVT__bus_errors_re;
        CData/*0:0*/ __PVT__ibus_ack;
        CData/*0:0*/ __PVT__dbus_ack;
        CData/*0:0*/ __PVT__ram_bus_ack;
        CData/*0:0*/ __PVT__interface0_ram_bus_cyc;
        CData/*0:0*/ __PVT__interface0_ram_bus_ack;
        CData/*3:0*/ __PVT__sram0_we;
        CData/*0:0*/ __PVT__interface1_ram_bus_cyc;
        CData/*0:0*/ __PVT__interface1_ram_bus_ack;
        CData/*3:0*/ __PVT__sram1_we;
        CData/*0:0*/ __PVT__uart_rxtx_re;
        CData/*0:0*/ __PVT__uart_rxtx_we;
        CData/*0:0*/ __PVT__uart_txfull_re;
        CData/*0:0*/ __PVT__uart_rxempty_re;
        CData/*0:0*/ __PVT__uart_tx_pending;
        CData/*0:0*/ __PVT__uart_tx_clear;
        CData/*0:0*/ __PVT__uart_tx_trigger_d;
        CData/*0:0*/ __PVT__uart_rx_pending;
        CData/*0:0*/ __PVT__uart_rx_clear;
        CData/*0:0*/ __PVT__uart_rx_trigger_d;
        CData/*1:0*/ __PVT__uart_status_status;
        CData/*0:0*/ __PVT__uart_status_re;
        CData/*1:0*/ __PVT__uart_pending_status;
        CData/*0:0*/ __PVT__uart_pending_re;
        CData/*1:0*/ __PVT__uart_pending_r;
        CData/*1:0*/ __PVT__uart_enable_storage;
        CData/*0:0*/ __PVT__uart_enable_re;
        CData/*0:0*/ __PVT__uart_txempty_re;
        CData/*0:0*/ __PVT__uart_rxfull_re;
        CData/*0:0*/ __PVT__uart_tx_fifo_readable;
        CData/*0:0*/ __PVT__uart_tx_fifo_syncfifo_writable;
        CData/*0:0*/ __PVT__uart_tx_fifo_syncfifo_re;
        CData/*4:0*/ __PVT__uart_tx_fifo_level0;
        CData/*3:0*/ __PVT__uart_tx_fifo_produce;
        CData/*3:0*/ __PVT__uart_tx_fifo_consume;
        CData/*3:0*/ __PVT__uart_tx_fifo_wrport_adr;
        CData/*0:0*/ __PVT__uart_tx_fifo_do_read;
        CData/*7:0*/ __PVT__uart_tx_fifo_fifo_out_payload_data;
        CData/*0:0*/ __PVT__uart_tx_fifo_fifo_out_first;
        CData/*0:0*/ __PVT__uart_tx_fifo_fifo_out_last;
        CData/*0:0*/ __PVT__uart_rx_fifo_readable;
        CData/*0:0*/ __PVT__uart_rx_fifo_syncfifo_writable;
        CData/*0:0*/ __PVT__uart_rx_fifo_syncfifo_re;
        CData/*4:0*/ __PVT__uart_rx_fifo_level0;
        CData/*3:0*/ __PVT__uart_rx_fifo_produce;
        CData/*3:0*/ __PVT__uart_rx_fifo_consume;
        CData/*3:0*/ __PVT__uart_rx_fifo_wrport_adr;
        CData/*0:0*/ __PVT__uart_rx_fifo_do_read;
        CData/*7:0*/ __PVT__uart_rx_fifo_fifo_out_payload_data;
        CData/*0:0*/ __PVT__uart_rx_fifo_fifo_out_first;
        CData/*0:0*/ __PVT__uart_rx_fifo_fifo_out_last;
        CData/*0:0*/ __PVT__timer_load_re;
        CData/*0:0*/ __PVT__timer_reload_re;
        CData/*0:0*/ __PVT__timer_en_storage;
        CData/*0:0*/ __PVT__timer_en_re;
        CData/*0:0*/ __PVT__timer_update_value_storage;
        CData/*0:0*/ __PVT__timer_update_value_re;
        CData/*0:0*/ __PVT__timer_value_re;
        CData/*0:0*/ __PVT__timer_zero_pending;
    };
    struct {
        CData/*0:0*/ __PVT__timer_zero_clear;
        CData/*0:0*/ __PVT__timer_zero_trigger_d;
        CData/*0:0*/ __PVT__timer_status_re;
        CData/*0:0*/ __PVT__timer_pending_re;
        CData/*0:0*/ __PVT__timer_pending_r;
        CData/*0:0*/ __PVT__timer_enable_storage;
        CData/*0:0*/ __PVT__timer_enable_re;
        CData/*0:0*/ __PVT__oe_re;
        CData/*0:0*/ __PVT__in_re;
        CData/*0:0*/ __PVT__out_re;
        CData/*0:0*/ __PVT__mode_re;
        CData/*0:0*/ __PVT__edge_re;
        CData/*0:0*/ __PVT__in_pads_n_d0;
        CData/*0:0*/ __PVT__eventsourceprocess0_pending;
        CData/*0:0*/ __PVT__eventsourceprocess0_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess0_clear;
        CData/*0:0*/ __PVT__eventsourceprocess0_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d1;
        CData/*0:0*/ __PVT__eventsourceprocess1_pending;
        CData/*0:0*/ __PVT__eventsourceprocess1_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess1_clear;
        CData/*0:0*/ __PVT__eventsourceprocess1_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d2;
        CData/*0:0*/ __PVT__eventsourceprocess2_pending;
        CData/*0:0*/ __PVT__eventsourceprocess2_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess2_clear;
        CData/*0:0*/ __PVT__eventsourceprocess2_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d3;
        CData/*0:0*/ __PVT__eventsourceprocess3_pending;
        CData/*0:0*/ __PVT__eventsourceprocess3_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess3_clear;
        CData/*0:0*/ __PVT__eventsourceprocess3_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d4;
        CData/*0:0*/ __PVT__eventsourceprocess4_pending;
        CData/*0:0*/ __PVT__eventsourceprocess4_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess4_clear;
        CData/*0:0*/ __PVT__eventsourceprocess4_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d5;
        CData/*0:0*/ __PVT__eventsourceprocess5_pending;
        CData/*0:0*/ __PVT__eventsourceprocess5_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess5_clear;
        CData/*0:0*/ __PVT__eventsourceprocess5_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d6;
        CData/*0:0*/ __PVT__eventsourceprocess6_pending;
        CData/*0:0*/ __PVT__eventsourceprocess6_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess6_clear;
        CData/*0:0*/ __PVT__eventsourceprocess6_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d7;
        CData/*0:0*/ __PVT__eventsourceprocess7_pending;
        CData/*0:0*/ __PVT__eventsourceprocess7_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess7_clear;
        CData/*0:0*/ __PVT__eventsourceprocess7_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d8;
        CData/*0:0*/ __PVT__eventsourceprocess8_pending;
        CData/*0:0*/ __PVT__eventsourceprocess8_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess8_clear;
        CData/*0:0*/ __PVT__eventsourceprocess8_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d9;
        CData/*0:0*/ __PVT__eventsourceprocess9_pending;
        CData/*0:0*/ __PVT__eventsourceprocess9_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess9_clear;
        CData/*0:0*/ __PVT__eventsourceprocess9_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d10;
        CData/*0:0*/ __PVT__eventsourceprocess10_pending;
    };
    struct {
        CData/*0:0*/ __PVT__eventsourceprocess10_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess10_clear;
        CData/*0:0*/ __PVT__eventsourceprocess10_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d11;
        CData/*0:0*/ __PVT__eventsourceprocess11_pending;
        CData/*0:0*/ __PVT__eventsourceprocess11_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess11_clear;
        CData/*0:0*/ __PVT__eventsourceprocess11_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d12;
        CData/*0:0*/ __PVT__eventsourceprocess12_pending;
        CData/*0:0*/ __PVT__eventsourceprocess12_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess12_clear;
        CData/*0:0*/ __PVT__eventsourceprocess12_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d13;
        CData/*0:0*/ __PVT__eventsourceprocess13_pending;
        CData/*0:0*/ __PVT__eventsourceprocess13_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess13_clear;
        CData/*0:0*/ __PVT__eventsourceprocess13_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d14;
        CData/*0:0*/ __PVT__eventsourceprocess14_pending;
        CData/*0:0*/ __PVT__eventsourceprocess14_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess14_clear;
        CData/*0:0*/ __PVT__eventsourceprocess14_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d15;
        CData/*0:0*/ __PVT__eventsourceprocess15_pending;
        CData/*0:0*/ __PVT__eventsourceprocess15_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess15_clear;
        CData/*0:0*/ __PVT__eventsourceprocess15_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d16;
        CData/*0:0*/ __PVT__eventsourceprocess16_pending;
        CData/*0:0*/ __PVT__eventsourceprocess16_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess16_clear;
        CData/*0:0*/ __PVT__eventsourceprocess16_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d17;
        CData/*0:0*/ __PVT__eventsourceprocess17_pending;
        CData/*0:0*/ __PVT__eventsourceprocess17_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess17_clear;
        CData/*0:0*/ __PVT__eventsourceprocess17_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d18;
        CData/*0:0*/ __PVT__eventsourceprocess18_pending;
        CData/*0:0*/ __PVT__eventsourceprocess18_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess18_clear;
        CData/*0:0*/ __PVT__eventsourceprocess18_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d19;
        CData/*0:0*/ __PVT__eventsourceprocess19_pending;
        CData/*0:0*/ __PVT__eventsourceprocess19_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess19_clear;
        CData/*0:0*/ __PVT__eventsourceprocess19_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d20;
        CData/*0:0*/ __PVT__eventsourceprocess20_pending;
        CData/*0:0*/ __PVT__eventsourceprocess20_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess20_clear;
        CData/*0:0*/ __PVT__eventsourceprocess20_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d21;
        CData/*0:0*/ __PVT__eventsourceprocess21_pending;
        CData/*0:0*/ __PVT__eventsourceprocess21_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess21_clear;
        CData/*0:0*/ __PVT__eventsourceprocess21_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d22;
        CData/*0:0*/ __PVT__eventsourceprocess22_pending;
        CData/*0:0*/ __PVT__eventsourceprocess22_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess22_clear;
        CData/*0:0*/ __PVT__eventsourceprocess22_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d23;
    };
    struct {
        CData/*0:0*/ __PVT__eventsourceprocess23_pending;
        CData/*0:0*/ __PVT__eventsourceprocess23_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess23_clear;
        CData/*0:0*/ __PVT__eventsourceprocess23_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d24;
        CData/*0:0*/ __PVT__eventsourceprocess24_pending;
        CData/*0:0*/ __PVT__eventsourceprocess24_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess24_clear;
        CData/*0:0*/ __PVT__eventsourceprocess24_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d25;
        CData/*0:0*/ __PVT__eventsourceprocess25_pending;
        CData/*0:0*/ __PVT__eventsourceprocess25_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess25_clear;
        CData/*0:0*/ __PVT__eventsourceprocess25_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d26;
        CData/*0:0*/ __PVT__eventsourceprocess26_pending;
        CData/*0:0*/ __PVT__eventsourceprocess26_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess26_clear;
        CData/*0:0*/ __PVT__eventsourceprocess26_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d27;
        CData/*0:0*/ __PVT__eventsourceprocess27_pending;
        CData/*0:0*/ __PVT__eventsourceprocess27_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess27_clear;
        CData/*0:0*/ __PVT__eventsourceprocess27_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d28;
        CData/*0:0*/ __PVT__eventsourceprocess28_pending;
        CData/*0:0*/ __PVT__eventsourceprocess28_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess28_clear;
        CData/*0:0*/ __PVT__eventsourceprocess28_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d29;
        CData/*0:0*/ __PVT__eventsourceprocess29_pending;
        CData/*0:0*/ __PVT__eventsourceprocess29_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess29_clear;
        CData/*0:0*/ __PVT__eventsourceprocess29_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d30;
        CData/*0:0*/ __PVT__eventsourceprocess30_pending;
        CData/*0:0*/ __PVT__eventsourceprocess30_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess30_clear;
        CData/*0:0*/ __PVT__eventsourceprocess30_trigger_d;
        CData/*0:0*/ __PVT__in_pads_n_d31;
        CData/*0:0*/ __PVT__eventsourceprocess31_pending;
        CData/*0:0*/ __PVT__eventsourceprocess31_trigger;
        CData/*0:0*/ __PVT__eventsourceprocess31_clear;
        CData/*0:0*/ __PVT__eventsourceprocess31_trigger_d;
        CData/*0:0*/ __PVT__sim_trace_storage;
        CData/*0:0*/ __PVT__sim_trace_re;
        CData/*7:0*/ __PVT__sim_marker_storage;
        CData/*0:0*/ __PVT__sim_marker_re;
        CData/*0:0*/ __PVT__finish_re;
        CData/*0:0*/ __PVT__finish_we;
        CData/*0:0*/ __PVT__mux_ready;
        CData/*0:0*/ __PVT__mux_source_valid;
        CData/*0:0*/ __PVT__mux_source_first;
        CData/*0:0*/ __PVT__mux_source_last;
        CData/*0:0*/ __PVT__mux_source_payload_hit;
        CData/*0:0*/ __PVT__mux_value_storage;
        CData/*0:0*/ __PVT__mux_value_re;
        CData/*0:0*/ __PVT__trigger_source_source_payload_hit;
        CData/*0:0*/ __PVT__trigger_enable_storage;
        CData/*0:0*/ __PVT__trigger_enable_re;
        CData/*0:0*/ __PVT__trigger_done_re;
        CData/*0:0*/ __PVT__trigger_mem_write_re;
        CData/*0:0*/ __PVT__trigger_mem_write_we;
        CData/*0:0*/ __PVT__trigger_mem_mask_re;
    };
    struct {
        CData/*0:0*/ __PVT__trigger_mem_value_re;
        CData/*0:0*/ __PVT__trigger_mem_full_re;
        CData/*0:0*/ __PVT__trigger_enable_d;
        CData/*0:0*/ __PVT__trigger_mem_asyncfifo_writable;
        CData/*0:0*/ __PVT__trigger_mem_asyncfifo_readable;
        CData/*0:0*/ __PVT__trigger_mem_graycounter0_ce;
        CData/*4:0*/ __PVT__trigger_mem_graycounter0_q;
        CData/*4:0*/ __PVT__trigger_mem_graycounter0_q_binary;
        CData/*4:0*/ __PVT__trigger_mem_graycounter0_q_next_binary;
        CData/*4:0*/ __PVT__trigger_mem_graycounter1_q;
        CData/*4:0*/ __PVT__trigger_mem_graycounter1_q_binary;
        CData/*4:0*/ __PVT__trigger_mem_graycounter1_q_next_binary;
        CData/*0:0*/ __PVT__trigger_mem_fifo_out_first;
        CData/*0:0*/ __PVT__trigger_mem_fifo_out_last;
        CData/*0:0*/ __PVT__trigger_done1;
        CData/*5:0*/ __PVT__trigger_count;
        CData/*0:0*/ __PVT__subsampler_source_valid;
        CData/*0:0*/ __PVT__subsampler_value_re;
        CData/*0:0*/ __PVT__subsampler_done;
        CData/*0:0*/ __PVT__storage_sink_sink_ready;
        CData/*0:0*/ __PVT__storage_enable_storage;
        CData/*0:0*/ __PVT__storage_enable_re;
        CData/*0:0*/ __PVT__storage_done_re;
        CData/*0:0*/ __PVT__storage_length_re;
        CData/*0:0*/ __PVT__storage_offset_re;
        CData/*0:0*/ __PVT__storage_mem_level_re;
        CData/*0:0*/ __PVT__storage_mem_data_re;
        CData/*0:0*/ __PVT__storage_enable_d;
        CData/*0:0*/ __PVT__storage_done0;
        CData/*0:0*/ __PVT__storage_mem_sink_valid;
        CData/*0:0*/ __PVT__storage_mem_sink_first;
        CData/*0:0*/ __PVT__storage_mem_sink_last;
        CData/*0:0*/ __PVT__storage_mem_source_ready;
        CData/*0:0*/ __PVT__storage_mem_readable;
        CData/*0:0*/ __PVT__storage_mem_syncfifo_writable;
        CData/*0:0*/ __PVT__storage_mem_syncfifo_re;
        CData/*0:0*/ __PVT__storage_mem_do_read;
        CData/*0:0*/ __PVT__storage_mem_fifo_out_first;
        CData/*0:0*/ __PVT__storage_mem_fifo_out_last;
        CData/*0:0*/ __PVT__storage_cdc_sink_valid;
        CData/*0:0*/ __PVT__storage_cdc_sink_first;
        CData/*0:0*/ __PVT__storage_cdc_sink_last;
        CData/*0:0*/ __PVT__storage_cdc_asyncfifo_writable;
        CData/*0:0*/ __PVT__storage_cdc_asyncfifo_readable;
        CData/*0:0*/ __PVT__storage_cdc_graycounter0_ce;
        CData/*2:0*/ __PVT__storage_cdc_graycounter0_q;
        CData/*2:0*/ __PVT__storage_cdc_graycounter0_q_binary;
        CData/*2:0*/ __PVT__storage_cdc_graycounter0_q_next_binary;
        CData/*2:0*/ __PVT__storage_cdc_graycounter1_q;
        CData/*2:0*/ __PVT__storage_cdc_graycounter1_q_binary;
        CData/*2:0*/ __PVT__storage_cdc_graycounter1_q_next_binary;
        CData/*0:0*/ __PVT__storage_cdc_fifo_out_first;
        CData/*0:0*/ __PVT__storage_cdc_fifo_out_last;
        CData/*0:0*/ __PVT__storage_wait;
        CData/*0:0*/ __PVT__storage_done1;
        CData/*0:0*/ __PVT__storage_read_source_ready;
        CData/*2:0*/ __PVT__storage_converter_mux;
        CData/*0:0*/ __PVT__storage_converter_last;
        CData/*0:0*/ __PVT__simsoc_we;
        CData/*0:0*/ __PVT__simsoc_wishbone_cyc;
        CData/*0:0*/ __PVT__simsoc_wishbone_ack;
        CData/*0:0*/ __PVT__shared_ack;
        CData/*1:0*/ __PVT__request;
        CData/*0:0*/ __PVT__grant;
    };
    struct {
        CData/*3:0*/ __PVT__slave_sel;
        CData/*3:0*/ __PVT__slave_sel_r;
        CData/*0:0*/ __PVT__error;
        CData/*0:0*/ __PVT__done;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_mux_value0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_mux_value0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_enable0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_enable0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_done_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_done_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask6_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask6_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask5_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask5_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask4_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask4_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask3_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask3_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask2_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask2_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask1_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask1_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_mask0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value6_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value6_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value5_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value5_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value4_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value4_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value3_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value3_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value2_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value2_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value1_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value1_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_value0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_full_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_trigger_mem_full_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_subsampler_value0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_subsampler_value0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_enable0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_enable0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_done_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_done_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_length0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_length0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_offset0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_offset0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_mem_level_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_mem_level_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_mem_data_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank0_storage_mem_data_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank1_reset0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank1_reset0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank1_scratch0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank1_scratch0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank1_bus_errors_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank1_bus_errors_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_oe0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_oe0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_in_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_in_we;
    };
    struct {
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_out0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_out0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_mode0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_mode0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_edge0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank2_edge0_we;
        CData/*0:0*/ __PVT__csr_bankarray_sel_r;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank4_marker0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank4_marker0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank5_enable0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank5_enable0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_load0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_load0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_reload0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_reload0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_en0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_en0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_update_value0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_update_value0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_value_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_value_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_ev_status_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_ev_status_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_ev_pending_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_ev_pending_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_ev_enable0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank6_ev_enable0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_txfull_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_txfull_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_rxempty_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_rxempty_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_ev_status_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_ev_status_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_ev_pending_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_ev_pending_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_ev_enable0_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_ev_enable0_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_txempty_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_txempty_we;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_rxfull_re;
        CData/*0:0*/ __PVT__csr_bankarray_csrbank7_rxfull_we;
        CData/*1:0*/ __PVT__simsoc_litescopeanalyzer_state;
        CData/*1:0*/ __PVT__simsoc_litescopeanalyzer_next_state;
        CData/*0:0*/ __PVT__simsoc_wishbone2csr_state;
        CData/*0:0*/ __PVT__simsoc_wishbone2csr_next_state;
        CData/*3:0*/ __PVT__array_muxed2;
        CData/*0:0*/ __PVT__array_muxed3;
        CData/*0:0*/ __PVT__array_muxed4;
        CData/*0:0*/ __PVT__array_muxed5;
        CData/*2:0*/ __PVT__array_muxed6;
        CData/*1:0*/ __PVT__array_muxed7;
        CData/*0:0*/ __PVT__multiregimpl0_regs0;
        CData/*0:0*/ __PVT__multiregimpl0_regs1;
        CData/*0:0*/ __PVT__multiregimpl1_regs0;
        CData/*0:0*/ __PVT__multiregimpl1_regs1;
        CData/*0:0*/ __PVT__multiregimpl2_regs0;
        CData/*0:0*/ __PVT__multiregimpl2_regs1;
        CData/*0:0*/ __PVT__multiregimpl3_regs0;
        CData/*0:0*/ __PVT__multiregimpl3_regs1;
        CData/*0:0*/ __PVT__multiregimpl4_regs0;
        CData/*0:0*/ __PVT__multiregimpl4_regs1;
        CData/*0:0*/ __PVT__multiregimpl5_regs0;
        CData/*0:0*/ __PVT__multiregimpl5_regs1;
        CData/*0:0*/ __PVT__multiregimpl6_regs0;
    };
    struct {
        CData/*0:0*/ __PVT__multiregimpl6_regs1;
        CData/*0:0*/ __PVT__multiregimpl7_regs0;
        CData/*0:0*/ __PVT__multiregimpl7_regs1;
        CData/*0:0*/ __PVT__multiregimpl8_regs0;
        CData/*0:0*/ __PVT__multiregimpl8_regs1;
        CData/*0:0*/ __PVT__multiregimpl9_regs0;
        CData/*0:0*/ __PVT__multiregimpl9_regs1;
        CData/*0:0*/ __PVT__multiregimpl10_regs0;
        CData/*0:0*/ __PVT__multiregimpl10_regs1;
        CData/*0:0*/ __PVT__multiregimpl11_regs0;
        CData/*0:0*/ __PVT__multiregimpl11_regs1;
        CData/*0:0*/ __PVT__multiregimpl12_regs0;
        CData/*0:0*/ __PVT__multiregimpl12_regs1;
        CData/*0:0*/ __PVT__multiregimpl13_regs0;
        CData/*0:0*/ __PVT__multiregimpl13_regs1;
        CData/*0:0*/ __PVT__multiregimpl14_regs0;
        CData/*0:0*/ __PVT__multiregimpl14_regs1;
        CData/*0:0*/ __PVT__multiregimpl15_regs0;
        CData/*0:0*/ __PVT__multiregimpl15_regs1;
        CData/*0:0*/ __PVT__multiregimpl16_regs0;
        CData/*0:0*/ __PVT__multiregimpl16_regs1;
        CData/*0:0*/ __PVT__multiregimpl17_regs0;
        CData/*0:0*/ __PVT__multiregimpl17_regs1;
        CData/*0:0*/ __PVT__multiregimpl18_regs0;
        CData/*0:0*/ __PVT__multiregimpl18_regs1;
        CData/*0:0*/ __PVT__multiregimpl19_regs0;
        CData/*0:0*/ __PVT__multiregimpl19_regs1;
        CData/*0:0*/ __PVT__multiregimpl20_regs0;
        CData/*0:0*/ __PVT__multiregimpl20_regs1;
        CData/*0:0*/ __PVT__multiregimpl21_regs0;
        CData/*0:0*/ __PVT__multiregimpl21_regs1;
        CData/*0:0*/ __PVT__multiregimpl22_regs0;
        CData/*0:0*/ __PVT__multiregimpl22_regs1;
        CData/*0:0*/ __PVT__multiregimpl23_regs0;
        CData/*0:0*/ __PVT__multiregimpl23_regs1;
        CData/*0:0*/ __PVT__multiregimpl24_regs0;
        CData/*0:0*/ __PVT__multiregimpl24_regs1;
        CData/*0:0*/ __PVT__multiregimpl25_regs0;
        CData/*0:0*/ __PVT__multiregimpl25_regs1;
        CData/*0:0*/ __PVT__multiregimpl26_regs0;
        CData/*0:0*/ __PVT__multiregimpl26_regs1;
        CData/*0:0*/ __PVT__multiregimpl27_regs0;
        CData/*0:0*/ __PVT__multiregimpl27_regs1;
        CData/*0:0*/ __PVT__multiregimpl28_regs0;
        CData/*0:0*/ __PVT__multiregimpl28_regs1;
        CData/*0:0*/ __PVT__multiregimpl29_regs0;
        CData/*0:0*/ __PVT__multiregimpl29_regs1;
        CData/*0:0*/ __PVT__multiregimpl30_regs0;
        CData/*0:0*/ __PVT__multiregimpl30_regs1;
        CData/*0:0*/ __PVT__multiregimpl31_regs0;
        CData/*0:0*/ __PVT__multiregimpl31_regs1;
        CData/*0:0*/ __PVT__multiregimpl32_regs0;
        CData/*0:0*/ __PVT__multiregimpl32_regs1;
        CData/*0:0*/ __PVT__multiregimpl33_regs0;
        CData/*0:0*/ __PVT__multiregimpl33_regs1;
        CData/*0:0*/ __PVT__multiregimpl34_regs0;
        CData/*0:0*/ __PVT__multiregimpl34_regs1;
        CData/*4:0*/ __PVT__multiregimpl35_regs0;
        CData/*4:0*/ __PVT__multiregimpl35_regs1;
        CData/*4:0*/ __PVT__multiregimpl36_regs0;
        CData/*4:0*/ __PVT__multiregimpl36_regs1;
        CData/*0:0*/ __PVT__multiregimpl38_regs0;
        CData/*0:0*/ __PVT__multiregimpl38_regs1;
        CData/*0:0*/ __PVT__multiregimpl41_regs0;
    };
    struct {
        CData/*0:0*/ __PVT__multiregimpl41_regs1;
        CData/*2:0*/ __PVT__multiregimpl43_regs0;
        CData/*2:0*/ __PVT__multiregimpl43_regs1;
        CData/*2:0*/ __PVT__multiregimpl44_regs0;
        CData/*2:0*/ __PVT__multiregimpl44_regs1;
        CData/*5:0*/ __PVT__mem_adr0;
        SData/*15:0*/ __PVT__subsampler_value_storage;
        SData/*15:0*/ __PVT__subsampler_counter;
        SData/*9:0*/ __PVT__storage_length_storage;
        SData/*9:0*/ __PVT__storage_offset_storage;
        SData/*9:0*/ __PVT__storage_mem_level0;
        SData/*8:0*/ __PVT__storage_mem_produce;
        SData/*8:0*/ __PVT__storage_mem_consume;
        SData/*8:0*/ __PVT__storage_mem_wrport_adr;
        SData/*9:0*/ __PVT__storage_mem_level1;
        SData/*9:0*/ __PVT__storage_count;
        SData/*13:0*/ __PVT__simsoc_adr;
        SData/*15:0*/ __PVT__multiregimpl37_regs0;
        SData/*15:0*/ __PVT__multiregimpl37_regs1;
        SData/*9:0*/ __PVT__multiregimpl39_regs0;
        SData/*9:0*/ __PVT__multiregimpl39_regs1;
        SData/*9:0*/ __PVT__multiregimpl40_regs0;
        SData/*9:0*/ __PVT__multiregimpl40_regs1;
        SData/*9:0*/ __PVT__multiregimpl42_regs0;
        SData/*9:0*/ __PVT__multiregimpl42_regs1;
        SData/*10:0*/ __PVT__sram_adr0;
        SData/*13:0*/ __PVT__main_ram_adr0;
        SData/*9:0*/ __PVT__storage_dat0;
        SData/*9:0*/ __PVT__storage_dat1;
        SData/*9:0*/ __PVT__storage_1_dat0;
        SData/*9:0*/ __PVT__storage_1_dat1;
        IData/*31:0*/ __PVT__scratch_storage;
        IData/*31:0*/ __PVT__bus_errors;
        IData/*31:0*/ __PVT__interrupt;
        IData/*31:0*/ __PVT__timer_load_storage;
        IData/*31:0*/ __PVT__timer_reload_storage;
        IData/*31:0*/ __PVT__timer_value_status;
        IData/*31:0*/ __PVT__timer_value;
        IData/*31:0*/ __PVT__oe_storage;
        IData/*31:0*/ __PVT__in_status;
        IData/*31:0*/ __PVT__out_storage;
        IData/*31:0*/ __PVT__mode_storage;
        IData/*31:0*/ __PVT__edge_storage;
        WData/*203:0*/ __PVT__mux_source_payload_data[7];
        WData/*203:0*/ __PVT__trigger_mem_mask_storage[7];
        WData/*203:0*/ __PVT__trigger_mem_value_storage[7];
        WData/*203:0*/ __PVT__trigger_mem_fifo_out_payload_mask[7];
        WData/*203:0*/ __PVT__trigger_mem_fifo_out_payload_value[7];
        WData/*203:0*/ __PVT__storage_mem_sink_payload_data[7];
        WData/*203:0*/ __PVT__storage_mem_fifo_out_payload_data[7];
        WData/*203:0*/ __PVT__storage_cdc_sink_payload_data[7];
        WData/*203:0*/ __PVT__storage_cdc_fifo_out_payload_data[7];
        IData/*31:0*/ __PVT__storage_converter_source_payload_data;
        IData/*31:0*/ __PVT__simsoc_dat_w;
        IData/*31:0*/ __PVT__simsoc_wishbone_dat_r;
        IData/*31:0*/ __PVT__shared_dat_r;
        IData/*19:0*/ __PVT__count;
        IData/*31:0*/ __PVT__csr_bankarray_interface0_bank_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_interface1_bank_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_interface2_bank_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_sram_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_interface3_bank_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_interface4_bank_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_interface5_bank_bus_dat_r;
    };
    struct {
        IData/*31:0*/ __PVT__csr_bankarray_interface6_bank_bus_dat_r;
        IData/*31:0*/ __PVT__csr_bankarray_interface7_bank_bus_dat_r;
        IData/*29:0*/ __PVT__array_muxed0;
        IData/*31:0*/ __PVT__array_muxed1;
        IData/*31:0*/ __PVT__rom_dat0;
        WData/*409:0*/ __PVT__storage_2_dat0[13];
        WData/*409:0*/ __PVT__storage_2_dat1[13];
        WData/*205:0*/ __PVT__storage_3_dat0[7];
        WData/*205:0*/ __PVT__storage_3_dat1[7];
        WData/*205:0*/ __PVT__storage_4_dat0[7];
        WData/*205:0*/ __PVT__storage_4_dat1[7];
        IData/*31:0*/ __PVT__rom[6061];
        IData/*31:0*/ __PVT__sram[2048];
        IData/*31:0*/ __PVT__main_ram[16384];
        CData/*7:0*/ __PVT__mem[37];
        SData/*9:0*/ __PVT__storage[16];
        SData/*9:0*/ __PVT__storage_1[16];
        WData/*409:0*/ __PVT__storage_2[16][13];
        WData/*205:0*/ __PVT__storage_3[512][7];
        WData/*205:0*/ __PVT__storage_4[4][7];
    };
    
    // LOCAL VARIABLES
    CData/*0:0*/ __Vcellinp__VexRiscv__reset;
    CData/*5:0*/ __Vdly__trigger_count;
    CData/*0:0*/ __Vdlyvset__storage_3__v0;
    CData/*1:0*/ __Vdlyvdim0__storage_4__v0;
    CData/*0:0*/ __Vdlyvset__storage_4__v0;
    CData/*0:0*/ __Vdly__interface0_ram_bus_ack;
    CData/*4:0*/ __Vdly__uart_rx_fifo_level0;
    CData/*0:0*/ __Vdly__interface1_ram_bus_ack;
    CData/*3:0*/ __Vdly__uart_tx_fifo_consume;
    CData/*4:0*/ __Vdly__uart_tx_fifo_level0;
    CData/*0:0*/ __Vdly__ram_bus_ack;
    CData/*4:0*/ __Vdlyvlsb__sram__v0;
    CData/*7:0*/ __Vdlyvval__sram__v0;
    CData/*0:0*/ __Vdlyvset__sram__v0;
    CData/*4:0*/ __Vdlyvlsb__sram__v1;
    CData/*7:0*/ __Vdlyvval__sram__v1;
    CData/*0:0*/ __Vdlyvset__sram__v1;
    CData/*4:0*/ __Vdlyvlsb__sram__v2;
    CData/*7:0*/ __Vdlyvval__sram__v2;
    CData/*0:0*/ __Vdlyvset__sram__v2;
    CData/*4:0*/ __Vdlyvlsb__sram__v3;
    CData/*7:0*/ __Vdlyvval__sram__v3;
    CData/*0:0*/ __Vdlyvset__sram__v3;
    CData/*4:0*/ __Vdlyvlsb__main_ram__v0;
    CData/*7:0*/ __Vdlyvval__main_ram__v0;
    CData/*0:0*/ __Vdlyvset__main_ram__v0;
    CData/*4:0*/ __Vdlyvlsb__main_ram__v1;
    CData/*7:0*/ __Vdlyvval__main_ram__v1;
    CData/*0:0*/ __Vdlyvset__main_ram__v1;
    CData/*4:0*/ __Vdlyvlsb__main_ram__v2;
    CData/*7:0*/ __Vdlyvval__main_ram__v2;
    CData/*0:0*/ __Vdlyvset__main_ram__v2;
    CData/*4:0*/ __Vdlyvlsb__main_ram__v3;
    CData/*7:0*/ __Vdlyvval__main_ram__v3;
    CData/*0:0*/ __Vdlyvset__main_ram__v3;
    CData/*3:0*/ __Vdlyvdim0__storage__v0;
    CData/*0:0*/ __Vdlyvset__storage__v0;
    CData/*3:0*/ __Vdlyvdim0__storage_1__v0;
    CData/*0:0*/ __Vdlyvset__storage_1__v0;
    CData/*3:0*/ __Vdlyvdim0__storage_2__v0;
    CData/*0:0*/ __Vdlyvset__storage_2__v0;
    SData/*9:0*/ __Vdly__storage_mem_level0;
    SData/*8:0*/ __Vdly__storage_mem_consume;
    SData/*15:0*/ __Vdly__subsampler_counter;
    SData/*8:0*/ __Vdlyvdim0__storage_3__v0;
    SData/*10:0*/ __Vdlyvdim0__sram__v0;
    SData/*10:0*/ __Vdlyvdim0__sram__v1;
    SData/*10:0*/ __Vdlyvdim0__sram__v2;
    SData/*10:0*/ __Vdlyvdim0__sram__v3;
    SData/*13:0*/ __Vdlyvdim0__main_ram__v0;
    SData/*13:0*/ __Vdlyvdim0__main_ram__v1;
    SData/*13:0*/ __Vdlyvdim0__main_ram__v2;
    SData/*13:0*/ __Vdlyvdim0__main_ram__v3;
    SData/*9:0*/ __Vdlyvval__storage__v0;
    SData/*9:0*/ __Vdlyvval__storage_1__v0;
    WData/*205:0*/ __Vdlyvval__storage_3__v0[7];
    WData/*205:0*/ __Vdlyvval__storage_4__v0[7];
    IData/*31:0*/ __Vdly__timer_value;
    IData/*31:0*/ __Vdly__bus_errors;
    WData/*409:0*/ __Vdlyvval__storage_2__v0[13];
    
    // INTERNAL VARIABLES
  private:
    Vsim__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vsim_sim);  ///< Copying not allowed
  public:
    Vsim_sim(const char* name = "TOP");
    ~Vsim_sim();
    
    // INTERNAL METHODS
    void __Vconfigure(Vsim__Syms* symsp, bool first);
    static void _combo__TOP__sim__46(Vsim__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
    void _ctor_var_reset_1() VL_ATTR_COLD;
  public:
    static void _initial__TOP__sim__1(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__sim__2(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__sim__3(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__sim__4(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__sim__5(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__sim__23(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__24(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__25(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__26(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__27(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__28(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__29(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__30(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__31(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__32(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__33(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__34(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__35(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__36(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__37(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__38(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__39(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__40(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__41(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__42(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__43(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__44(Vsim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__sim__45(Vsim__Syms* __restrict vlSymsp);
    static void _settle__TOP__sim__10(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__11(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__12(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__13(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__14(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__15(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__16(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__6(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__7(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__8(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__sim__9(Vsim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
  private:
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
