#!/usr/bin/env bash
# Autogenerated by LiteX / git: 552d7bdb
set -e -u -x -o pipefail

quartus_map --read_settings_files=on  --write_settings_files=off terasic_de10lite -c terasic_de10lite
quartus_fit --read_settings_files=off --write_settings_files=off terasic_de10lite -c terasic_de10lite
quartus_asm --read_settings_files=off --write_settings_files=off terasic_de10lite -c terasic_de10lite
quartus_sta terasic_de10lite -c terasic_de10lite